import { AppointmentItem } from "./types";

export const initialSampleAppointments: AppointmentItem[] = [
  {
    id: "app-1",
    titulo: "Visita ao Decorado • Villa Platz Beach",
    tipo: "VISITA",
    dataInicio: "2026-10-01T14:30:00Z",
    dataFim: "2026-10-01T15:30:00Z",
    status: "AGENDADO",
    lead: { id: "l-1", nome: "Dr. Marcelo Cavalcante", telefone: "85998124455" },
    property: { id: "p-1", nome: "Villa Platz Beach", endereco: "Av. Beira-Mar, 1200", bairro: "Meireles" },
    observacoes: "Cliente busca 3 suítes frente mar, sol poente mitigado.",
    user: { id: "u-1", nome: "Carlos Eduardo" },
  },
  {
    id: "app-2",
    titulo: "Reunião de Alinhamento de Proposta",
    tipo: "PROPOSTA",
    dataInicio: "2026-10-01T16:00:00Z",
    dataFim: "2026-10-01T17:00:00Z",
    status: "AGENDADO",
    lead: { id: "l-2", nome: "Juliana Albuquerque", telefone: "85987332211" },
    property: { id: "p-2", nome: "Platz Oceanfront Residence", endereco: "Rua Dep. Moreira da Rocha, 450", bairro: "Meireles" },
    observacoes: "Análise de fluxo de pagamento durante as obras.",
    user: { id: "u-2", nome: "Ana Paula" },
  },
  {
    id: "app-3",
    titulo: "Coleta e Conferência de Documentação",
    tipo: "DOCUMENTACAO",
    dataInicio: "2026-10-02T10:00:00Z",
    dataFim: "2026-10-02T11:00:00Z",
    status: "AGENDADO",
    lead: { id: "l-3", nome: "Roberto Simões", telefone: "85991448899" },
    property: { id: "p-3", nome: "Residencial Aldeota Platz", endereco: "Rua Barbosa de Freitas, 880", bairro: "Aldeota" },
    user: { id: "u-1", nome: "Carlos Eduardo" },
  },
  {
    id: "app-4",
    titulo: "Retorno telefônico sobre proposta enviada",
    tipo: "RETORNO",
    dataInicio: "2026-10-03T11:30:00Z",
    dataFim: "2026-10-03T12:00:00Z",
    status: "AGENDADO",
    lead: { id: "l-4", nome: "Fernando Guimarães", telefone: "85992334455" },
    property: { id: "p-1", nome: "Villa Platz Beach" },
    user: { id: "u-3", nome: "Mariana Costa" },
  },
  {
    id: "app-5",
    titulo: "Lembrete: Enviar minuta contratual para cartório",
    tipo: "LEMBRETE",
    dataInicio: "2026-10-01T11:00:00Z",
    dataFim: "2026-10-01T11:30:00Z",
    status: "CONCLUIDO",
    lead: { id: "l-5", nome: "Beatriz Mota", telefone: "85994445566" },
    user: { id: "u-1", nome: "Carlos Eduardo" },
  },
];
