import { IntegrationItem } from "./types";

export const initialIntegrations: IntegrationItem[] = [
  {
    id: "meta-ads",
    nome: "Meta Ads (Facebook & Instagram)",
    descricao: "Captação automática de leads em tempo real dos formulários de cadastro do Facebook e Instagram.",
    categoria: "Mídia Paga",
    status: "Conectado",
    logo: "meta",
    ativo: true,
    contaConectada: "Connect Platz Imóveis (ID: 104928349284)",
    ultimaSincronizacao: "Hoje às 18:55",
    leadsRecebidos: 248,
    acaoPendente: "1 formulário novo detectado no Gerenciador de Anúncios precisa de validação de campos.",
    regras: {
      distribuicao: "roleta",
      etapaInicial: "Novo Lead",
    },
  },
  {
    id: "google-ads",
    nome: "Google Ads (Lead Extension)",
    descricao: "Sincronização de leads captados através de extensões de formulário da rede de pesquisa e campanhas Discovery.",
    categoria: "Mídia Paga",
    status: "Conectado",
    logo: "google",
    ativo: true,
    contaConectada: "MCC Platz Imobiliária (089-234-1122)",
    ultimaSincronizacao: "Hoje às 17:30",
    leadsRecebidos: 112,
    regras: {
      distribuicao: "roleta",
      etapaInicial: "Novo Lead",
    },
  },
  {
    id: "grupo-olx",
    nome: "Grupo OLX (Zap Imóveis & Viva Real)",
    descricao: "Integração via Carga XML e Webhook oficial para receber contatos dos maiores portais imobiliários do Brasil.",
    categoria: "Portais Imobiliários",
    status: "Plugin Oficial",
    logo: "olx",
    ativo: true,
    contaConectada: "Credencial Portal ID #884920",
    ultimaSincronizacao: "Hoje às 18:20",
    leadsRecebidos: 184,
    regras: {
      distribuicao: "roleta",
      etapaInicial: "Novo Lead",
    },
  },
  {
    id: "dream-casa",
    nome: "Dream Casa",
    descricao: "Recebimento direto de propostas e solicitações de visitas do portal Dream Casa.",
    categoria: "Portais Imobiliários",
    status: "Conectado",
    logo: "dreamcasa",
    ativo: true,
    contaConectada: "Chave API Ativa",
    ultimaSincronizacao: "Hoje às 14:10",
    leadsRecebidos: 45,
    regras: {
      distribuicao: "roleta",
      etapaInicial: "Novo Lead",
    },
  },
  {
    id: "chaves-na-mao",
    nome: "Chaves na Mão",
    descricao: "Portal especializado em imóveis na planta e lançamentos com disparo direto para o funil.",
    categoria: "Portais Imobiliários",
    status: "Conectado",
    logo: "chavesnamao",
    ativo: true,
    contaConectada: "Token Anunciante Ativo",
    ultimaSincronizacao: "Hoje às 12:40",
    leadsRecebidos: 38,
    regras: {
      distribuicao: "roleta",
      etapaInicial: "Novo Lead",
    },
  },
  {
    id: "landing-page",
    nome: "Landing Page Oficial (WordPress & Elementor)",
    descricao: "Captura de leads das landing pages de lançamentos, formulários customizados e catálogos.",
    categoria: "Site e Landing Pages",
    status: "Plugin Oficial",
    logo: "wordpress",
    ativo: true,
    contaConectada: "https://connectplatz.com.br",
    ultimaSincronizacao: "Hoje às 19:04",
    leadsRecebidos: 320,
    regras: {
      distribuicao: "roleta",
      etapaInicial: "Novo Lead",
    },
  },
  {
    id: "api-webhooks",
    nome: "API & Webhooks Customizados",
    descricao: "Endpoint RESTful para conexão com ferramentas externas, n8n, Make e sistemas legados de construtoras.",
    categoria: "Desenvolvimento",
    status: "Avançado",
    logo: "webhook",
    ativo: true,
    contaConectada: "Token JWT emitido para Produção",
    ultimaSincronizacao: "Hoje às 19:10",
    leadsRecebidos: 89,
    regras: {
      distribuicao: "roleta",
      etapaInicial: "Novo Lead",
    },
  },
];
