import { LeadDetail } from "@/components/crm/LeadDrawer";

export const initialSampleLeads: LeadDetail[] = [
  {
    id: "lead-1",
    nome: "Ana Paula Silva",
    telefone: "(47) 99872-3312",
    email: "anapaula.silva@gmail.com",
    temperatura: "QUENTE",
    source: "Meta Ads",
    stageId: "stage-1",
    opportunityValue: 480000,
    empreendimentoInteresse: "Reserva Imperial",
    cidadeInteresse: "Balneário Camboriú",
    rendaDeclarada: 18500,
    score: 88,
    corretor: { id: "user-1", nome: "Lucas Pinheiro" },
    tags: ["Cliente Quente", "Meta Ads"],
    slaDueAt: new Date(Date.now() + 15 * 60000).toISOString(),
    slaBreached: false,
    compromissosCount: 1,
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    id: "lead-2",
    nome: "Carlos Eduardo Santos",
    telefone: "(47) 98711-4455",
    email: "carlos.santos@outlook.com",
    temperatura: "MORNO",
    source: "WhatsApp",
    stageId: "stage-1",
    opportunityValue: 350000,
    empreendimentoInteresse: "Platz Home Studio",
    cidadeInteresse: "Itajaí",
    rendaDeclarada: 12000,
    score: 64,
    corretor: { id: "user-2", nome: "Camila Duarte" },
    tags: ["Follow-up/Sem Resposta", "WhatsApp"],
    slaDueAt: new Date(Date.now() + 45 * 60000).toISOString(),
    slaBreached: false,
    compromissosCount: 2,
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  {
    id: "lead-3",
    nome: "Marcos Vinicius Ferraz",
    telefone: "(11) 97722-1100",
    email: "marcos.ferraz@techcorp.com.br",
    temperatura: "QUENTE",
    source: "Landing Page",
    stageId: "stage-2",
    opportunityValue: 890000,
    empreendimentoInteresse: "Ocean Breeze Tower",
    cidadeInteresse: "Balneário Camboriú",
    rendaDeclarada: 32000,
    score: 95,
    corretor: { id: "user-1", nome: "Lucas Pinheiro" },
    tags: ["Cliente Quente", "Potencial"],
    slaDueAt: new Date(Date.now() + 90 * 60000).toISOString(),
    slaBreached: false,
    compromissosCount: 1,
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
  },
  {
    id: "lead-4",
    nome: "Juliana Mendes",
    telefone: "(48) 99123-9988",
    email: "juliana.mendes@adv.br",
    temperatura: "MORNO",
    source: "Google Ads",
    stageId: "stage-3",
    opportunityValue: 560000,
    empreendimentoInteresse: "Platz Jardins",
    cidadeInteresse: "Joinville",
    rendaDeclarada: 21000,
    score: 68,
    corretor: { id: "user-3", nome: "Robson Carvalho" },
    tags: ["Cliente reagendou"],
    slaDueAt: new Date(Date.now() + 720 * 60000).toISOString(),
    slaBreached: false,
    compromissosCount: 3,
    createdAt: new Date(Date.now() - 1440 * 60000).toISOString(),
  },
  {
    id: "lead-5",
    nome: "Roberto Faria de Almeida",
    telefone: "(47) 98400-3321",
    email: "roberto.almeida@empresa.com",
    temperatura: "QUENTE",
    source: "Orgânico",
    stageId: "stage-4",
    opportunityValue: 1250000,
    empreendimentoInteresse: "Mansão Ilha da Paz",
    cidadeInteresse: "Balneário Camboriú",
    rendaDeclarada: 55000,
    score: 97,
    corretor: { id: "user-1", nome: "Lucas Pinheiro" },
    tags: ["Cliente Quente", "Potencial"],
    slaDueAt: new Date(Date.now() + 300 * 60000).toISOString(),
    slaBreached: false,
    compromissosCount: 2,
    createdAt: new Date(Date.now() - 2880 * 60000).toISOString(),
  },
  {
    id: "lead-6",
    nome: "Fernanda Cristina Rocha",
    telefone: "(47) 99654-1122",
    email: "fernanda.rocha@uol.com.br",
    temperatura: "FRIO",
    source: "Catálogo",
    stageId: "stage-1",
    opportunityValue: 290000,
    empreendimentoInteresse: "Residencial Bela Vista",
    cidadeInteresse: "Camboriú",
    rendaDeclarada: 7500,
    score: 36,
    isBolsao: true,
    corretor: null,
    tags: ["Bolsão"],
    slaDueAt: new Date(Date.now() - 60 * 60000).toISOString(),
    slaBreached: true,
    compromissosCount: 0,
    createdAt: new Date(Date.now() - 4000 * 60000).toISOString(),
  },
];
