import { PropertyCardData } from "./PropertyProductCard";

export const initialSampleProperties: PropertyCardData[] = [
  {
    id: "prop-1",
    nome: "Villa Platz Beach",
    slug: "villa-platz-beach",
    tipoCadastro: "EMPREENDIMENTO",
    modalidade: "AMBOS",
    estagioObra: "Lançamento",
    valorVenda: 1250000,
    valorDiaria: 1200,
    bairro: "Porto das Dunas",
    cidade: "Aquiraz",
    descricao: "Exclusivo condomínio pé na areia com bangalôs e apartamentos de alto padrão frente mar.",
    fotos: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=60"],
    caracteristicas: { area_m2: 142, quartos: 3, suites: 3, vagas: 2 },
    diferenciais: ["Pé na Areia", "Piscina com Borda Infinita", "Heliponto", "Beach Club"],
    exibirNaLandingPage: true,
    construtora: "Platz Urbanismo",
  },
  {
    id: "prop-2",
    nome: "Reserva Imperial",
    slug: "reserva-imperial",
    tipoCadastro: "EMPREENDIMENTO",
    modalidade: "VENDA",
    estagioObra: "Em Obras",
    valorVenda: 2450000,
    bairro: "Meireles",
    cidade: "Fortaleza",
    descricao: "Torre imponente no coração do Meireles com plantas amplas e acabamento nobre em mármore.",
    fotos: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=60"],
    caracteristicas: { area_m2: 210, quartos: 4, suites: 4, vagas: 3 },
    diferenciais: ["Vista Panorâmica Mar", "Varanda Gourmet Integrada", "Spa Privativo", "Concierge 24h"],
    exibirNaLandingPage: true,
    construtora: "Moura Dubeux",
  },
  {
    id: "prop-3",
    nome: "Platz Oceanfront Residence",
    slug: "platz-oceanfront-residence",
    tipoCadastro: "EMPREENDIMENTO",
    modalidade: "VENDA",
    estagioObra: "Pronto para Morar",
    valorVenda: 3800000,
    bairro: "Meireles",
    cidade: "Fortaleza",
    descricao: "Apartamentos de altíssimo luxo na orla de Fortaleza, 1 por andar com pé direito duplo.",
    fotos: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=60"],
    caracteristicas: { area_m2: 360, quartos: 4, suites: 4, vagas: 4 },
    diferenciais: ["Pé Direito Duplo", "Elevador com Biometria", "Adega Climatizada", "Academia Life Fitness"],
    exibirNaLandingPage: true,
    construtora: "Platz Urbanismo",
  },
  {
    id: "prop-4",
    nome: "Residencial Aldeota Platz",
    slug: "residencial-aldeota-platz",
    tipoCadastro: "EMPREENDIMENTO",
    modalidade: "VENDA",
    estagioObra: "Lançamento",
    valorVenda: 890000,
    bairro: "Aldeota",
    cidade: "Fortaleza",
    descricao: "Plantas inteligentes e funcionais para famílias contemporâneas próximo à Praça Portugal.",
    fotos: ["https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&auto=format&fit=crop&q=60"],
    caracteristicas: { area_m2: 95, quartos: 3, suites: 2, vagas: 2 },
    diferenciais: ["Coworking Integrado", "Rooftop Lounge", "Piscina Aquecida", "Carregador Carro Elétrico"],
    exibirNaLandingPage: true,
    construtora: "Diagonal",
  },
  {
    id: "prop-5",
    nome: "Solarium Porto das Dunas",
    slug: "solarium-porto-das-dunas",
    tipoCadastro: "EMPREENDIMENTO",
    modalidade: "VERANEIO_TEMPORADA",
    estagioObra: "Pronto para Morar",
    valorVenda: 980000,
    valorDiaria: 950,
    bairro: "Porto das Dunas",
    cidade: "Aquiraz",
    descricao: "Resort residencial ao lado do parque aquático, ideal para renda com locação de temporada.",
    fotos: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&auto=format&fit=crop&q=60"],
    caracteristicas: { area_m2: 88, quartos: 2, suites: 2, vagas: 1 },
    diferenciais: ["Complexo Aquático", "Quadra de Beach Tennis", "Restaurante Operacional", "Gestão de Aluguel"],
    exibirNaLandingPage: true,
    construtora: "Colmeia",
  },
  {
    id: "prop-6",
    nome: "Platz Home Studio",
    slug: "platz-home-studio",
    tipoCadastro: "AVULSO",
    modalidade: "VENDA",
    estagioObra: "Pronto para Morar",
    valorVenda: 350000,
    bairro: "Itajaí",
    cidade: "Itajaí",
    descricao: "Studio moderno mobiliado e decorado, alta rentabilidade por metragem quadrada.",
    fotos: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=60"],
    caracteristicas: { area_m2: 42, quartos: 1, suites: 1, vagas: 1 },
    diferenciais: ["Totalmente Mobiliado", "Fechadura Digital", "Lavanderia Compartilhada"],
    exibirNaLandingPage: true,
    construtora: "Platz Urbanismo",
  },
];
